modLoader = "kotori_scala"
loaderVersion = "[3.3.0,)"
issueTrackerURL = "https://github.com/bdew-minecraft/bdlib/issues"
license = "MIT"

[[mods]]
modId = "bdlib"
version = "${file.jarVersion}"
displayName = "BdLib"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/bdlib"
authors = "bdew"
description = '''
This is a collection of generic code used by my other mods.
'''

[[dependencies.bdlib]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bdlib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
